### PR TITLE
Add newer open source projects to Ozzie

### PR DESCRIPTION
**Pull request by josecanhelp**
Fixes issue #11

### CODE REVIEW

**Comment by darkboywonder** [comment]
I noticed we haven't added LaravelTricks yet either. Should we consider that as well?

**Comment by josecanhelp** [comment]
@darkboywonder I think Ozzie is meant to monitor our open source packages. Laravel Tricks is a private repo.

**Comment by mattstauffer** [comment]
Yah, @darkboywonder, the moment we do a thorough scrub of Laravel Tricks to make sure it's OK to put it public, we should get it on here.

**Comment by mattstauffer** [comment]
Thanks @josecanhelp!

**Pull request merged**
